version: '3.8'

services:

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - petclinic_app_data:/var/lib/mysql

  pet:
    image: pet:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - MYSQL_URL=jdbc:mysql://mysql/petclinic

volumes:
  petclinic_app_data:
